export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_RESET_SUCCESS = 'CATEGORY_RESET_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'
export const CATEGORY_DETAILS_RESET = 'CATEGORY_DETAILS_RESET'

export const CATEGORY_PAY_REQUEST = 'CATEGORY_PAY_REQUEST'
export const CATEGORY_PAY_SUCCESS = 'CATEGORY_PAY_SUCCESS'
export const CATEGORY_PAY_FAIL = 'CATEGORY_PAY_FAIL'
export const CATEGORY_PAY_RESET = 'CATEGORY_PAY_RESET'

export const CATEGORY_DELIVERED_REQUEST = 'CATEGORY_DELIVERED_REQUEST'
export const CATEGORY_DELIVERED_SUCCESS = 'CATEGORY_DELIVERED_SUCCESS'
export const CATEGORY_DELIVERED_FAIL = 'CATEGORY_DELIVERED_FAIL'
export const CATEGORY_DELIVERED_RESET = 'CATEGORY_DELIVERED_RESET'

export const CATEGORY_LIST_MY_REQUEST = 'CATEGORY_LIST_MY_REQUEST'
export const CATEGORY_LIST_MY_SUCCESS = 'CATEGORY_LIST_MY_SUCCESS'
export const CATEGORY_LIST_MY_FAIL = 'CATEGORY_LIST_MY_FAIL'
export const CATEGORY_LIST_MY_RESET = 'CATEGORY_LIST_MY_RESET'

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORYS_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'
export const GET_CATEGORIES_RESET = 'GET_CATEGORIES_RESET'

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST'
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS'
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL'
export const GET_ALL_CATEGORIES_RESET = 'GET_ALL_CATEGORIES_RESET'

export const CATEGORIES_DELETE_REQUEST = 'CATEGORIES_DELETE_REQUEST'
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS'
export const CATEGORIES_DELETE_FAIL = 'CATEGORIES_DELETE_FAIL'
export const CATEGORIES_DELETE_CLEAR_MESSAGE = 'CATEGORIES_DELETE_CLEAR_MESSAGE'
